# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_comments_paths_year": "00_read_data.ipynb",
         "read_comm_csv": "00_read_data.ipynb",
         "read_comm_csvs": "00_read_data.ipynb",
         "log_step": "01_preproc.ipynb",
         "conv_to_lowerc": "01_preproc.ipynb",
         "rm_punct": "01_preproc.ipynb",
         "tokenize": "01_preproc.ipynb",
         "count_toks": "01_preproc.ipynb",
         "rem_short_comments": "01_preproc.ipynb",
         "clean_comments": "01_preproc.ipynb",
         "Corpus": "02_type_emb.ipynb",
         "train_model": "02_type_emb.ipynb",
         "intersection_align_gensim": "02_type_emb.ipynb",
         "smart_procrustes_align_gensim": "02_type_emb.ipynb",
         "measure_distances": "02_type_emb.ipynb",
         "get_nearest_neighbours_models": "02_type_emb.ipynb",
         "get_subr_counts": "03_communities.ipynb",
         "plot_subr_counts": "03_communities.ipynb"}

modules = ["read_data.py",
           "preproc.py",
           "type_emb.py",
           "communities.py"]

doc_url = "https://wuqui.github.io/neocov/"

git_url = "https://github.com/wuqui/neocov/tree/master/"

def custom_doc_links(name): return None
