# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_comments_paths_year": "00_read_data.ipynb",
         "read_comm_csv": "00_read_data.ipynb",
         "read_comm_csvs": "00_read_data.ipynb"}

modules = ["read_data.py",
           "preproc.py"]

doc_url = "https://wuqui.github.io/neocov/"

git_url = "https://github.com/wuqui/neocov/tree/master/"

def custom_doc_links(name): return None
