# AUTOGENERATED! DO NOT EDIT! File to edit: 01_preproc.ipynb (unless otherwise specified).

__all__ = ['conv_to_lowerc', 'rm_punct', 'tokenize', 'detect_short_doc', 'clean_docs']

# Cell
import re

# Cell
def conv_to_lowerc(doc):
    return doc.lower()

# Cell
def rm_punct(doc):
    return re.sub(r'[^\w\s]+', ' ', doc)

# Cell
def tokenize(doc):
    return doc.split()

# Cell
def detect_short_doc(doc, limit=10):
    if len(doc) >= limit:
        return False
    else:
        return True

# Cell
def clean_docs(docs):
    docs_clean = docs\
        .apply(conv_to_lowerc)\
        .apply(rm_punct)\
        .apply(tokenize)\
        .where(lambda x : x.apply(detect_short_doc) == False)\
        .dropna()
    return docs_clean