# AUTOGENERATED! DO NOT EDIT! File to edit: 00_read_data.ipynb (unless otherwise specified).

__all__ = ['get_comments_paths_year']

# Cell
from pathlib import Path

# Cell
def get_comments_paths_year(COMMENTS_DIR, YEAR):
    comments_dir_path = Path(COMMENTS_DIR)
    comments_paths = list(comments_dir_path.glob(f'{YEAR}*.csv'))
    return comments_paths